all:
	eyapp -P ExpList.eyp 
	eyapp -TC noPackratSolvedExpRGconcept.eyp
	./noPackratSolvedExpRGconcept.pm -t -i -m 1 -c '2-3 3*4 5+2'

other:
	./noPackratSolvedExpRGconcept.pm -t -i -m 1 -c '2-3 3*4 5+2 7 9-1'
	
	
